name: Scrape FEMA shelters

on:
  push:
  workflow_dispatch:
  schedule:
  - cron:  '3,33 * * * *'

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scrape with retries
      run: |
        max_attempts=3
        count=0
        until [ $count -ge $max_attempts ]; do
          count=$(($count + 1))
          echo "Attempt $count to fetch data..."
          
          # Download to temp file and get HTTP status code
          temp_file=$(mktemp)
          http_code=$(curl -s -w "%{http_code}" 'https://gis.fema.gov/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=FEMA:FEMANSSOpenShelters&maxFeatures=250&outputFormat=json' -o "$temp_file")
          
          if [ "$http_code" = "504" ]; then
            echo "Received a 504 Gateway Timeout error. Logging and exiting without failure."
            echo "504 Gateway Timeout encountered at $(date -u)" >> gateway_timeout_log.txt
            exit 0
          elif [ "$http_code" = "200" ]; then
            echo "Data downloaded successfully. Contents:"
            cat "$temp_file"
            echo "Attempting to process with jq..."
            if jq '.' "$temp_file" > fema-shelters.json; then
              echo "Data processed successfully."
              rm "$temp_file"
              break
            else
              echo "jq processing failed."
            fi
          else
            echo "Download failed with HTTP code $http_code."
          fi
          
          if [ $count -ge $max_attempts ]; then
            echo "All $max_attempts attempts failed. Exiting with error."
            exit 1
          fi
          echo "Trying again in 10 seconds..."
          sleep 10
        done
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
